version: '3'
services:

    #Tomcat
  webserver:
    image: tomcat:8.5.16-jre8-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:8080"
    volumes:
     - ./webappps:/usr/local/tomcat/webapps/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456mfh
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
        - ./dump/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
